/**
 * Generate Zod schemas from JSON Schema files.
 *
 * This script reads JSON Schema files generated by Go (source of truth)
 * and converts them to Zod schemas with TypeScript types.
 *
 * Pipeline: Go types → JSON Schema → Zod Schema → TypeScript types
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const SCHEMA_DIR = resolve(ROOT, '..', 'schema');
const OUTPUT_DIR = resolve(ROOT, 'src', 'schema');

interface SchemaConfig {
  input: string;
  output: string;
  name: string;
}

const schemas: SchemaConfig[] = [
  {
    input: resolve(SCHEMA_DIR, 'journey-roadmap.schema.json'),
    output: resolve(OUTPUT_DIR, 'journey-roadmap.ts'),
    name: 'JourneyRoadmap',
  },
];

function generateHeader(name: string, inputPath: string): string {
  return `/**
 * ${name} - Zod Schema
 *
 * AUTO-GENERATED from JSON Schema. DO NOT EDIT.
 * Source: ${inputPath.replace(ROOT + '/', '')}
 *
 * Pipeline: Go types → JSON Schema → Zod Schema → TypeScript types
 *
 * To regenerate: pnpm generate:schema
 */

import { z } from 'zod';

`;
}

function processSchema(config: SchemaConfig): void {
  const { input, output, name } = config;

  if (!existsSync(input)) {
    console.warn(`⚠️  Skipping ${name}: ${input} not found`);
    console.warn(`   Run 'go run schema/cmd/generate/main.go' to generate JSON Schema`);
    return;
  }

  console.log(`📄 Processing ${name}...`);

  const jsonSchema = JSON.parse(readFileSync(input, 'utf-8'));

  // Generate Zod schema code with named export
  const schemaName = name.replace(/[^a-zA-Z0-9]/g, '');
  const zodCode = jsonSchemaToZod(jsonSchema, {
    module: 'esm',
    name: schemaName,
    type: true, // Generate TypeScript types
  });

  // Add header and write file
  const header = generateHeader(name, input);
  const fullCode = header + zodCode;

  writeFileSync(output, fullCode, 'utf-8');
  console.log(`✅ Generated ${output.replace(ROOT + '/', '')}`);
}

function main(): void {
  console.log('🔄 Generating Zod schemas from JSON Schema...\n');

  for (const config of schemas) {
    try {
      processSchema(config);
    } catch (error) {
      console.error(`❌ Error processing ${config.name}:`, error);
      process.exit(1);
    }
  }

  console.log('\n✨ Schema generation complete!');
}

main();
