package assessment

import (
	"fmt"
	"time"

	"github.com/grokify/prism-roadmap/canvas"
	"github.com/grokify/prism-roadmap/prioritization"
	"github.com/plexusone/structured-evaluation/rubric"
)

// OpportunityRef points at the OpportunitySpec (and optionally the roadmap
// item) an assessment evaluates. The assessment does not embed or copy the
// spec — it references it by ID, since the spec is a human-authored
// discovery document with its own lifecycle while the assessment is a
// regenerable judgment record (prism-roadmap TRD D1).
type OpportunityRef struct {
	// SpecID is the canvas.OpportunitySpec.Metadata.ID this assessment
	// evaluates.
	SpecID string `json:"specId"`

	// RMIID optionally links to the roadmap item (RMI-<REPOSLUG>-NNN) this
	// opportunity corresponds to, if one has been created.
	RMIID string `json:"rmiId,omitempty"`
}

// RefFromSpec builds an OpportunityRef from a canvas.OpportunitySpec.
func RefFromSpec(spec *canvas.OpportunitySpec) OpportunityRef {
	return OpportunityRef{SpecID: spec.Metadata.ID}
}

// AssessmentCycle records where an assessment sits in its opportunity's
// regenerate history (prism-roadmap PRD FR1 / TRD D1): assessments are
// regenerated per review cycle, not edited in place, so a full audit trail
// survives. Corrections that must persist (a governance override, a
// corrected effort estimate) attach as their own records at compile/review
// time (TRD D6) rather than mutating a past cycle.
type AssessmentCycle struct {
	// Number is the 1-indexed cycle number for this opportunity (1 = first
	// assessment produced).
	Number int `json:"number"`

	// AssessedAt is when this cycle's judgment was produced. Supplied by the
	// caller rather than computed internally, so recompute stays
	// reproducible from stored data.
	AssessedAt time.Time `json:"assessedAt"`

	// SupersedesID is the ID of the assessment this one replaces as current,
	// if any. Empty for an opportunity's first assessment.
	SupersedesID string `json:"supersedesId,omitempty"`

	// Current reports whether this is the latest assessment for its
	// opportunity. Exactly one assessment per opportunity should be current
	// at a time; the persistence layer (omniroadmap) enforces that
	// invariant across records — MarkSuperseded only flips this flag.
	Current bool `json:"current"`
}

// OpportunityAssessment is the canonical judgment record for one review
// cycle of one opportunity: definition reference, judge/provenance
// metadata, cycle history, prioritization, portfolio classification, OKR
// links, and capability references. Raw judge inputs are stored (answers,
// evidence refs); resolved values (MoSCoW tier, RICE score) are always
// computed on demand via MoSCoW()/ComputeRICE, never stored redundantly —
// the same discipline RICEScoreResult already follows, so a resolved value
// can never silently drift out of sync with the answers behind it.
//
// Unlike OpportunitySpec, an OpportunityAssessment is not something a human
// edits in place: it is regenerated by a judge run against a versioned
// rubric. Corrections happen via a new cycle (NextCycle) or, for
// portfolio-review-time governance decisions, via a dedicated override
// record (TRD D6) — never by mutating a past assessment's fields.
type OpportunityAssessment struct {
	// ID is the assessment identifier, conventionally OA-NNN, unique across
	// the assessment corpus (an omniroadmap-assigned sequence). Distinct
	// from Opportunity.SpecID: many assessments (one per cycle) share one
	// opportunity/spec.
	ID string `json:"id"`

	// Opportunity is what this assessment evaluates.
	Opportunity OpportunityRef `json:"opportunity"`

	// Title is denormalized from the referenced spec so a reviewer scanning
	// a ranked list sees what an opportunity is without opening the spec.
	Title string `json:"title"`

	// Judge carries the model/rubric/session that produced this assessment,
	// reused from structured-evaluation rather than reinventing judge
	// provenance (rubric.JudgeMetadata already carries RubricID/Version,
	// token usage, and trace linkage). Nil until a scoring rubric has been
	// run against this cycle.
	Judge *rubric.JudgeMetadata `json:"judge,omitempty"`

	// Cycle records this assessment's place in its opportunity's regenerate
	// history.
	Cycle AssessmentCycle `json:"cycle"`

	// MoSCoWAnswers are this cycle's raw MoSCoWLadder judge answers. Resolve
	// via MoSCoW(), never store the resolved tier directly.
	MoSCoWAnswers []ThresholdAnswer `json:"moscowAnswers,omitempty"`

	// RICE is this cycle's RICE inputs (Reach, Impact/Confidence answers,
	// Effort estimate). Resolve a score via ComputeRICE(*a.RICE). Nil until
	// a RICE rubric has been run.
	RICE *RICEAssessment `json:"rice,omitempty"`

	// Compass is this cycle's COMPASS-RICE assessment: a profile-normalized
	// evidence-to-score judgment (see CompassAssessment). Resolve a score
	// via ResolveCompassRICE(a.Compass) — its cross-profile-comparable
	// score is intended to supersede the legacy single-scale RICE for any
	// opportunity that has adopted a profile. Nil until a COMPASS-RICE
	// assessment has been ingested.
	Compass *CompassAssessment `json:"compass,omitempty"`

	// Dimensions are this cycle's portfolio-dimension classifications —
	// Kano, Market Investment Horizon, and any custom Category/Tags
	// dimensions (RMI-PRISMROADMAP-005/006). Descriptive only: never a
	// RankingPolicy input.
	Dimensions []DimensionAssignment `json:"dimensions,omitempty"`

	// Contributions link this opportunity to the OKRs it advances
	// (RMI-PRISMROADMAP-007). Not a RankingPolicy input.
	Contributions []OKRContribution `json:"contributions,omitempty"`

	// Capabilities link this opportunity to the prism-capability
	// capabilities it enables, improves, or depends on
	// (RMI-PRISMROADMAP-008). Not a RankingPolicy input.
	Capabilities []CapabilityReference `json:"capabilities,omitempty"`
}

// MoSCoW resolves this cycle's MoSCoW priority from MoSCoWAnswers. Returns
// prioritization.MoSCoWWontHave if no answers have been recorded yet or no
// criterion is satisfied with evidence (see ResolveMoSCoWPriority).
func (a *OpportunityAssessment) MoSCoW() prioritization.MoSCoWPriority {
	return ResolveMoSCoWPriority(a.MoSCoWAnswers)
}

// NewOpportunityAssessment creates the first assessment cycle for an
// opportunity.
func NewOpportunityAssessment(id string, opportunity OpportunityRef, title string, assessedAt time.Time) *OpportunityAssessment {
	return &OpportunityAssessment{
		ID:          id,
		Opportunity: opportunity,
		Title:       title,
		Cycle: AssessmentCycle{
			Number:     1,
			AssessedAt: assessedAt,
			Current:    true,
		},
	}
}

// NextCycle creates the next assessment cycle for the same opportunity,
// carrying forward Opportunity and Title and linking back via
// Cycle.SupersedesID. The caller is responsible for persisting both records
// and calling MarkSuperseded on the previous current assessment.
func (a *OpportunityAssessment) NextCycle(id string, assessedAt time.Time) *OpportunityAssessment {
	return &OpportunityAssessment{
		ID:          id,
		Opportunity: a.Opportunity,
		Title:       a.Title,
		Cycle: AssessmentCycle{
			Number:       a.Cycle.Number + 1,
			AssessedAt:   assessedAt,
			SupersedesID: a.ID,
			Current:      true,
		},
	}
}

// DimensionAssignment returns this assessment's assignment for the given
// dimension ID, or nil if none was recorded.
func (a *OpportunityAssessment) DimensionAssignment(dimensionID string) *DimensionAssignment {
	for i := range a.Dimensions {
		if a.Dimensions[i].DimensionID == dimensionID {
			return &a.Dimensions[i]
		}
	}
	return nil
}

// PersonDays returns this cycle's RICE effort estimate, or 0 if no RICE
// assessment has been recorded yet.
func (a *OpportunityAssessment) PersonDays() float64 {
	if a.RICE == nil {
		return 0
	}
	return a.RICE.Effort.Expected
}

// HasEvidence reports whether this assessment cites at least one Evidence
// ID anywhere in its rubric answers, Reach, or OKR contributions — used to
// decide whether an opportunity report's evidence-log appendix has
// anything to show.
func (a *OpportunityAssessment) HasEvidence() bool {
	for _, ans := range a.MoSCoWAnswers {
		if len(ans.EvidenceIDs) > 0 {
			return true
		}
	}
	if a.RICE != nil {
		if len(a.RICE.Reach.EvidenceIDs) > 0 {
			return true
		}
		for _, ans := range a.RICE.ImpactAnswers {
			if len(ans.EvidenceIDs) > 0 {
				return true
			}
		}
		for _, ans := range a.RICE.ConfidenceAnswers {
			if len(ans.EvidenceIDs) > 0 {
				return true
			}
		}
	}
	if a.Compass != nil && len(a.Compass.Claims) > 0 {
		return true
	}
	for _, d := range a.Dimensions {
		for _, ans := range d.Answers {
			if len(ans.EvidenceIDs) > 0 {
				return true
			}
		}
	}
	for _, c := range a.Contributions {
		if len(c.EvidenceIDs) > 0 {
			return true
		}
	}
	return false
}

// HasRubricAnswers reports whether this assessment has any recorded
// MoSCoW/RICE/dimension rubric answers to trace — used to decide whether an
// opportunity report's rubric-trace appendix has anything to show.
func (a *OpportunityAssessment) HasRubricAnswers() bool {
	if len(a.MoSCoWAnswers) > 0 {
		return true
	}
	if a.RICE != nil && (len(a.RICE.ImpactAnswers) > 0 || len(a.RICE.ConfidenceAnswers) > 0) {
		return true
	}
	for _, d := range a.Dimensions {
		if len(d.Answers) > 0 {
			return true
		}
	}
	return false
}

// EvidenceReferences extracts every EvidenceRef this assessment cites,
// across MoSCoW answers, RICE (Reach/Impact/Confidence), portfolio
// dimension answers, and OKR contributions — the same structures
// HasEvidence() walks, but returning the full citation list rather than a
// boolean. Used to build an EvidenceIndex across an assessment corpus
// (e.g. omniroadmap's evidence staleness sweep).
func (a *OpportunityAssessment) EvidenceReferences() []EvidenceRef {
	var refs []EvidenceRef
	add := func(questionID string, evidenceIDs []string) {
		for _, evID := range evidenceIDs {
			refs = append(refs, EvidenceRef{EvidenceID: evID, AssessmentID: a.ID, QuestionID: questionID})
		}
	}

	for _, ans := range a.MoSCoWAnswers {
		add("moscow."+ans.LevelID, ans.EvidenceIDs)
	}
	if a.RICE != nil {
		add("rice.reach", a.RICE.Reach.EvidenceIDs)
		for _, ans := range a.RICE.ImpactAnswers {
			add("rice.impact."+ans.LevelID, ans.EvidenceIDs)
		}
		for _, ans := range a.RICE.ConfidenceAnswers {
			add("rice.confidence."+ans.LevelID, ans.EvidenceIDs)
		}
	}
	if a.Compass != nil {
		for _, cl := range a.Compass.Claims {
			if cl == nil || cl.ID == "" {
				continue
			}
			refs = append(refs, EvidenceRef{EvidenceID: cl.ID, AssessmentID: a.ID, QuestionID: "compass." + string(a.Compass.ProfileID)})
		}
	}
	for _, d := range a.Dimensions {
		for _, ans := range d.Answers {
			add("dimension."+d.DimensionID+"."+ans.QuestionID, ans.EvidenceIDs)
		}
	}
	for _, c := range a.Contributions {
		questionID := "okr." + c.ObjectiveID
		if c.KeyResultID != "" {
			questionID += "." + c.KeyResultID
		}
		add(questionID, c.EvidenceIDs)
	}

	return refs
}

// MarkSuperseded flips Cycle.Current to false. Call this on the previous
// current assessment when persisting a new cycle produced via NextCycle.
func (a *OpportunityAssessment) MarkSuperseded() {
	a.Cycle.Current = false
}

// Validate returns an error if required fields are missing.
func (a *OpportunityAssessment) Validate() error {
	if a.ID == "" {
		return fmt.Errorf("id is required")
	}
	if a.Opportunity.SpecID == "" {
		return fmt.Errorf("opportunity.specId is required")
	}
	if a.Title == "" {
		return fmt.Errorf("title is required")
	}
	if a.Cycle.Number < 1 {
		return fmt.Errorf("cycle.number must be >= 1")
	}
	if a.Cycle.AssessedAt.IsZero() {
		return fmt.Errorf("cycle.assessedAt is required")
	}
	return nil
}
